dave-inc/charts

common/Chart.yaml, common/templates/NOTES.txt, common/templates/_helpers.tpl, common/templates/configmap.yaml, common/templates/deployment.yaml, common/templates/hpa.yaml, common/templates/ingress.yaml, common/templates/service.yaml, common/templates/tests/test-connection.yaml, common/values.yaml
- Defines Values.env as a map for environment variables
- Uses the sha256 checksum of the stringified `env` variable as an
annotation on the Deployment, to trigger a rolling deployment when the
ConfigMap values change
Example:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: loomis-staging-common-configmap
labels:
helm.sh/chart: common-0.2.0
app.kubernetes.io/name: common
app.kubernetes.io/instance: loomis-staging
app.kubernetes.io/version: "1.17.0"
app.kubernetes.io/managed-by: Helm
data:
foo: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: loomis-staging-common
labels:
helm.sh/chart: common-0.2.0
app.kubernetes.io/name: common
app.kubernetes.io/instance: loomis-staging
app.kubernetes.io/version: "1.17.0"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1 …
```
=> Add ConfigMap to Deployment

common/Chart.yaml, common/templates/deployment.yaml
Uses the image tag as a version variable
https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#overview
=> Add DD_VERSION env variable

common/Chart.yaml, common/templates/deployment.yaml
This way a more specific config will override the existing config map
(when it's shared)
https://github.com/dave-inc/sre/pull/42
=> Change the order in which configmaps are applied

common/Chart.yaml, common/templates/deployment.yaml, common/values.yaml
banking uses prefixed variants: `banking-production` instead of just `production`
=> NRD - allow overriding DD_ENV in deployments

common/Chart.yaml, common/templates/deployment.yaml
- Specify `args` in a deployment (for use with secret management)
- Added DD_AGENT_HOST to default env values for [hot-shots](https://www.npmjs.com/package/hot-shots) compatibility (the Dave StatsD client)
=> NRD - deployment updates

common/Chart.yaml, common/templates/backendconfig.yaml, common/templates/ingress.yaml, common/values.yaml
- BackendConfig fix, includes securityPolicy and healthCheck by default
- With cloudArmor enabled Tls section under Ingress is not required
=> healthCheck and tls section fix

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/certificate-cloudarmor.yaml, charts/common/templates/ingress-cloudarmor.yaml, charts/common/templates/serviceaccount.yaml, charts/common/values.yaml
- Validate alias name
- More descriptive message for required fields
- Move `host` and `secretName` to `certificate` section in `cloudArmor`
=> Validate alias, required fields and move host to certificate section in cloudarmor

charts/job/Chart.yaml, charts/job/templates/cronjob.yaml, charts/job/templates/job.yaml
the dd version tag was not always wrapped in quotes, so when using a git commit short hash there could be a bug ( there currently is with a deployment 😅 ) where the short hash has no letters in it, and is read as an int64. this should force a string for any value passed in
=> fix the quotes for dd version

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/deployment.yaml, charts/common/templates/ingress.yaml, charts/common/templates/service-cloudarmor.yaml, charts/common/values.yaml
- change the default CA cert secret name to include `-ca-` in the name to avoid conflicts with nginx
- Add label `run` to deployments  with value `common.name`
- Set default secret name for nginx to `$hostwithdashestls` if no name was given.
- Removed check for `.Values.service.enabled` on CA setup as the services are not shared.
- Minimal documentation changes to match the changes above
=> [SRE-1087] common chart minor bug fixes

charts/common/Chart.yaml
Release `common-0.8.0`
[common-0.8.0-beta.3](https://github.com/dave-inc/charts/releases/tag/common-0.8.0-beta.3)
- Change the default CA cert secret name to include -ca- in the name to avoid conflicts with nginx
- Add label run to deployments with value common.name
- Set default secret name for nginx tls to $hostwithdashestls if no name was given.
- Removed check for .Values.service.enabled on CA setup as the services are not shared.
- Minimal documentation changes to match the changes above
[common-0.8.0-beta.2](https://github.com/dave-inc/charts/releases/tag/common-0.8.0-beta.2)
- Added Startup Probe
- Added custom Probes for Liveness, Readiness and Startup to use different checks mechanism as: exec, grcp and tcpSocket.
- https://kubernetes.io/docs/tasks/configure-pod-container/configur …
=> Release 0.8.0

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/configmap-customconfig.yaml, charts/common/templates/deployment.yaml, charts/common/values.yaml
**Ticket**
[SRE-1614](https://demoforthedaves.atlassian.net/browse/SRE-1614)
Support optional config files through a configmap
`helm template --set name=xyz,project=xyz,customConfig.enabled=true,customConfig.data.xyz=asdf .`
Apply it to `promotions-api`.
=> [SRE-1614] Support optional config files through a configmap

charts/common/Chart.yaml, charts/common/templates/pdb.yaml, charts/common/values.yaml
**Ticket**
[SRE-2044](https://demoforthedaves.atlassian.net/browse/SRE-2044)
PodDisruptionBudget support for Common Chart
Disabled by default.
minAvailable and maxUnavailable are mutually exclusive, only one should be set.
If podDisruptionBudget is enabled but no minAvailable or maxUnavailable fields
are set, the PodDisruptionTemplate template will default to `minAvailable: 15%`.
The value for minAvailable and maxUnavailable should either be set to an integer
or a percentage.  For more information see the official documentation:
[https://kubernetes.io/docs/tasks/run-application/configure-pdb/](https://kubernetes.io/docs/tasks/run-application/configure-pdb/)
Local testing via `helm template`
**How will you confirm this change is …
=> [SRE-2044] Add support for PodDisruptionBudget

charts/common/templates/vpa.yaml, charts/common/values.yaml
**Ticket**
[SRE-2045](https://demoforthedaves.atlassian.net/browse/SRE-2045)
`VerticalPodAutoscaler`
*Requires* Vertical Pod Autoscaling feature to be enabled on the target GKE cluster
`VirtualPodAutoscaler`'s updateMode is hardcoded to `"Off"`.  Purposely not allowing
`"Initial"`, `"Auto"` and `"Recreate"` updateModes to be used as further understanding
of how the VPA work is required, specially if used in conjuction with HPAs.  When
updateMode is set to `"Off"`, no vertical autoscaling actions are taken.  The purpose
of enabling the VPA with updateMode set to `"Off"` is to get recommendations on what
initial settings should be for resource requests and limits based on current
workloads.
For more information refer to the GKE documentation on VPAs: …
=> [SRE-2045] Add support for VerticalPodAutoscaler

charts/common/Chart.yaml, charts/common/templates/deployment.yaml, charts/common/templates/service-cloudarmor.yaml, charts/common/templates/service.yaml, charts/common/values.yaml
Adding the option to override the default pod selector labels on deployment, pods and services 
``` # Source: promotions-api/charts/promotions-api/templates/deployment.yaml
apiVersion: apps/v1
@@ -60,8 +59,7 @@
replicas: 3
selector:
matchLabels:
-      app.kubernetes.io/name: promotions-api
-      app.kubernetes.io/instance: promotions-api
+      customSelectorLabel: overridede_value
```
This helps when importing deployments to avoid recreation
$ kubectl diff -f TMP-new-promotions-api.yaml
The Deployment "promotions-api" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"promotions-api", "app.kubernetes.io/name":"promotions-api"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
=> [NT] Add option to override default pod selector labels

charts/common/Chart.yaml, charts/common/templates/deployment.yaml, charts/common/values.yaml
Adding options to override the value of `common.name`  from the DD_SERVICE_NAME env variable when APM is enabled.
```
apm:
enabled: true
datadogServiceName: custom_dd_service_name
```
Also adding an option to skip the definition of `DD_SERVICE_NAME` altogether so the DD integration takes the name of the app from package.json ( required only for some deployment imports from legacy ) without affecting the definition of other DD required environment variables
=> [SRE-1867] Adding options dd_service_name env overrides

charts/common/Chart.yaml, charts/common/templates/hpa.yaml
Rollback api version until we complete migrations to 1.23
=> Rollback api version until we complete migrations to 1.23

charts/job/Chart.yaml, charts/job/templates/cronjob.yaml, charts/job/templates/job.yaml, charts/job/values.yaml
**Ticket**
[SEC-3121](https://demoforthedaves.atlassian.net/browse/SEC-3121)
Adding support for cronjob sidecars to mount secrets in support of dave-inc/sre#3222
[SEC-3121]: https://demoforthedaves.atlassian.net/browse/SEC-3121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SEC-3121] Support external secrets in cronjob sidecars

charts/tekton-cron-jobs/.helmignore, charts/tekton-cron-jobs/Chart.yaml, charts/tekton-cron-jobs/README.md, charts/tekton-cron-jobs/templates/_helpers.tpl, charts/tekton-cron-jobs/templates/cron.yaml, charts/tekton-cron-jobs/templates/event-listener.yaml, charts/tekton-cron-jobs/templates/trigger.yaml, charts/tekton-cron-jobs/templates/triggerbindings.yaml, charts/tekton-cron-jobs/values-example.yaml, charts/tekton-cron-jobs/values.yaml
Adds a chart to assist in running tekton pipelines on a schedule.
Works by triggering job from k8s's CronJob via curl.
<details><summary>Example output</summary>
```yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
name: sentinel-cron
spec:
schedule: "*/1 * * * *"
jobTemplate:
spec:
template:
spec:
containers:
- name: trigger
image: curlimages/curl
args: ["curl", "-X", "POST", "--data", "{\"job\": \"sentinel\"}", "el-tekton-cron.$(NAMESPACE).svc.cluster.local:8080"]
env:
- name: NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
restartPolicy: Never
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
name: tekton-cron
spec:
triggers:
- sentinel-cron-trigger
resources:
kubernetesResource:
replicas: 2
spec:
template:
spec:
serviceAccountName: …
```
=> [DPE-262] Chart for scheduled tekton jobs

charts/common/Chart.yaml, charts/common/templates/deployment.yaml, charts/common/values.yaml
**Ticket**
[SRE-3115](https://demoforthedaves.atlassian.net/browse/SRE-3115)
- Add http headers for liveness/readiness/startup probes
n/a
n/a
[SRE-3115]: https://demoforthedaves.atlassian.net/browse/SRE-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SRE-3115] Add http headers for liveness/readiness/startup probes

charts/job/Chart.yaml, charts/job/values.yaml
Adding default to job chart to help debugging, prevent concurrency and prevent execution when updating schedule
=> Adding some default to job chart

charts/tekton-common/Chart.yaml, charts/tekton-common/templates/rbac.yaml
Add permissions, so that a Tekton task can run another pipeline.
=> Update tekton-deployer role permissions

charts/tekton-common/Chart.yaml, charts/tekton-common/templates/rbac.yaml
Although the pipeline is triggered, the task shows this for each task that runs:
```
Unable to get TaskRun: [taskruns.tekton.dev](http://taskruns.tekton.dev/) "<taskrun>" is forbidden: User "system:serviceaccount:dpe:tekton-pipelines" cannot get resource "taskruns" in API group "[tekton.dev](http://tekton.dev/)" in the namespace "dpe"
```
=> Add taskruns permissions to tekton-deployer role

charts/tekton-common/Chart.yaml, charts/tekton-common/templates/rbac.yaml
This allows for a Tekton task to run a pipeline and stream the logs.
=> Add permissions to tekton-deployer role

charts/tekton-common/templates/secrets-slack.yaml
**Ticket**
[DPE-341](https://demoforthedaves.atlassian.net/browse/DPE-341)
add: Slack secret for Tekton
This secret contains the Slack bot token to use the Slack API
n/a
n/a
[DPE-341]: https://demoforthedaves.atlassian.net/browse/DPE-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-341] - add: Slack secret for Tekton

charts/common/Chart.yaml, charts/common/templates/deployment.yaml, charts/common/values.yaml
PR to 
- enable by default the use of topologySpreadConstraints to spread pod of the same deployment across nodes and AZs
- Set default replicas to 2 pods if not overridden by the values file
Currently, only the following parameters can be modified, selectorLabes are populated by the templating system
```
topologySpreadConstraints:
zone:
enabled: true
maxSkew: 1
topologyKey: topology.kubernetes.io/zone
whenUnsatisfiable: ScheduleAnyway
node:
enabled: true
maxSkew: 1
topologyKey: kubernetes.io/hostname
whenUnsatisfiable: ScheduleAnyway
```
diff for a deployment using this version
```
--- control.yaml	2023-07-18 18:32:29
+++ test4.yaml	2023-07-18 19:11:32
@@ -5,7 +5,7 @@
metadata:
name: financier
labels:
-    helm.sh/chart: financier-0.8.4-beta
+    helm.sh/chart: financier-0.8.4-beta.1 …
```
=> Enabling options for topologySpreadConstraints

charts/job/Chart.yaml, charts/job/templates/cronjob.yaml, charts/job/templates/job.yaml, charts/job/values.yaml
**Ticket**
[SEC-4694](https://demoforthedaves.atlassian.net/browse/SEC-4694)
Adding a new value `existingSecretList` to support multiple secrets being loaded into the env for a single job. 
By applying the templates with it until it was accurate.
It will be used immediately after deploy to confirm function.
[SEC-4694]: https://demoforthedaves.atlassian.net/browse/SEC-4694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SEC-4694] Add Job Chart Multiple Secret Support

charts/workflow/Chart.yaml, charts/workflow/templates/role.yaml, charts/workflow/templates/rolebinding.yaml, charts/workflow/templates/workflowtemplate.yaml, charts/workflow/values.yaml
**BREAKING CHANGES:**
Removes  `serviceAccount.existingNameSA`
removes the extra directive in favor of the combination of 
```
serviceAccount.name: this-sa-already-exist
serviceAccount.create: false
```
Changes the behavior on creating and re-using existing Service Accounts (SA),  supports the next 3 scenarios:
1 - Use the `workflows` SA and take no other action, this is the **default** scenario, the SA should already be defined if your common chart deployment has the migration template enabled. 
```
serviceAccount:
name: workflow
create: false
addRBAC: false
```
2- Re-use an SA from a different deployment, ie. overdraft uses the `overdraft`  SA, the SA object already exists in the cluster, and just the RBAC needs to be added.
You will also need to add the necessary log bucket permissions …
=> Adding fix for use of  custom and existing SA on custom workflows chart

charts/common/Chart.yaml, charts/common/values.yaml
Changelog:
Common chart
- Decreases the default CPU request from 100m to 50m to cloudsql-proxy
- Add default memory request of 25Mi to cloudsql-proxy
- Add default memory limit of 256Mi to cloudsql-proxy
New default requests and limits based on VPA and GKE metrics recommendations:
```
Container Name:  cloudsql-proxy
Lower Bound:
Cpu:     8m
Memory:  12582912
Target:
Cpu:     15m
Memory:  13631488
Uncapped Target:
Cpu:     15m
Memory:  13631488
Upper Bound:
Cpu:     15m
Memory:  13631488
```
=> Adding memory request and limits to cloudsql-proxy sidecar

charts/common/Chart.yaml, charts/common/templates/deployment.yaml, charts/common/values.yaml
**Ticket**
[SRE-4508](https://demoforthedaves.atlassian.net/browse/SRE-4508)
- Add initContainer secret fetch stage to validate the intended secrets have been populated before doing a complete replicaset rollout
n/a
n/a
[SRE-4508]: https://demoforthedaves.atlassian.net/browse/SRE-4508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SRE-4508] Add initContainer secret fetch stage to validate the intended secrets

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/deployment.yaml, charts/common/templates/workflowtemplate.yaml, charts/common/values.yaml
https://demoforthedaves.atlassian.net/browse/SRE-4700
- In order for CloudSQL proxies pass Kyverno policies the following changes are implemented in this new version.
- Move to cloud-sql-proxy v2 as default for common-charts (deployments/sidecar)
- This would ensure K8s monitor the health of the sidecar:
- readinessProbe
- livenessProbe
- startupProbe
- Simplify definition of the cloudsqlProxy in values.yaml it can now be defined as
```
cloudsqlProxy:
enabled: true
instanceConnectionName: internal-1-4825:us-central1:staging-2
migrationTemplate:
enabled: true
```
- If this version goes well sets the path to apply this changes for the jobs (cronjob) chart
- Ref: 
- https://github.com/GoogleCloudPlatform/cloud-sql-proxy
- https://github.com/GoogleCloudPlatform/cloud-sql-proxy/tree/main/exampl …
=> Move to cloud-sql-proxy v2 and add probes by default

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/deployment.yaml, charts/common/templates/workflowtemplate.yaml, charts/common/values.yaml
https://demoforthedaves.atlassian.net/browse/SRE-4987
- Fix bug where v2 version can end with no `args` nor `command` in template
- Get `instanceConnectionName` from either variables or `args`or `command` and use it with proper image version
- Add `--quiet` because by default is logging "Accepted connection ..." for every connection
- Remove socket path file during preStop
- Comments on default and fail messages
=> Add some logic to find instanceConnectionName and switch to quiet logs

charts/kyverno-policies/Chart.yaml, charts/kyverno-policies/templates/common-ingress.yaml
[SRE-4816](https://demoforthedaves.atlassian.net/browse/SRE-4816)
- Policy alerts on any nginx-public either with or without CloudArmor (nginx-public should be disabled or removed from code)
- Applies to all environments
[SRE-4816]: https://demoforthedaves.atlassian.net/browse/SRE-4816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SRE-4816 - Policy to detect nginx-public

charts/job/Chart.yaml, charts/job/templates/cronjob.yaml, charts/job/templates/job.yaml, charts/job/values.yaml
A note on review: I did move the main container to the top of the list.  All the new stuff is between `{{ cloudsqlProxy}}` blocks (and a few other obvious places).  the `sideCar` blocks are cut-and-paste changes.
Copying the ticket description here for what this is all about.
---
Kubernetes Jobs are a notorious pain for the cloudsql-proxy sidecar pattern we use for database access.  The problem is that a Job is only considered complete when all containers have exited, but the cloudsql-proxy container won’t naturally exit when the main pod does. 
We’ve long used a chunk of boilerplate copied from a [GitHub comment](https://github.com/kubernetes/kubernetes/issues/25908#issuecomment-365924958) that makes the cloudsql-proxy container exit when the main job container exits.  This boilerplate …
=> PLAT-1491 abstract cloudsql-proxy in crons

.github/workflows/release.yml
**Ticket**
[SRE-4961](https://demoforthedaves.atlassian.net/browse/SRE-4961)
- Use `self-hosted-small-spot` instead of the legacy runners
n/a
n/a
[SRE-4961]: https://demoforthedaves.atlassian.net/browse/SRE-4961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SRE-4961] Migrate `release.yml` to the new gha runners

charts/cloudsql-proxy/Chart.yaml, charts/cloudsql-proxy/README.md, charts/cloudsql-proxy/templates/_helpers.tpl, charts/cloudsql-proxy/templates/configmap.yaml, charts/cloudsql-proxy/templates/deployment.yaml, charts/cloudsql-proxy/templates/pdb.yaml, charts/cloudsql-proxy/templates/service.yaml, charts/cloudsql-proxy/templates/serviceaccount.yaml, charts/cloudsql-proxy/values.yaml
This Helm chart deploys a CloudSQL Proxy v2 instance in Kubernetes, facilitating connections to Google Cloud SQL databases. It's designed to provide an alternative to the sidecar pattern, allowing internal Kubernetes service name-based connections when TCP connections are required.
https://demoforthedaves.atlassian.net/browse/SRE-5012
=> Sre 5012/cloudsql proxy

charts/job/Chart.yaml
This will make available the prod release of job-0.2.0-beta.0 to streamline cloudsql-proxy sidecar containers in the CronJob
=> SRE-5261: Creating release version 0.2.0 for job Chart

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/backendconfig.yaml, charts/common/templates/certificate-cloudarmor.yaml, charts/common/templates/deployment-canary.yaml, charts/common/templates/deployment.yaml, charts/common/templates/destinationrule.yaml, charts/common/templates/frontendconfig.yaml, charts/common/templates/gateway-cloudarmor.yaml, charts/common/templates/gateway.yaml, charts/common/templates/hpa-canary.yaml, charts/common/templates/ingress-cloudarmor.yaml, charts/common/templates/ingress.yaml, charts/common/templates/service-cloudarmor.yaml, charts/common/templates/virtualservice.yaml, charts/common/values.yaml
Adds concept of canary to run side-by-side with existing setup. 
This has been tested in devel-2 cluster in different states: "legacy", "canary + internal lb", "canary + CloudArmor". 
Added the concept of "canary migration" to the chart. Concept only relevant to applications that use CloudArmor.
If `canary.migration` is true, then two CA sets of resources are generated: one for "legacy" (i.e. the way it before this PR) and one for "Cloud Service Mesh". This is due to resources being deployed to a different namespaces.
=> [BEI-808] Add concept of canary to common chart

charts/common/Chart.yaml, charts/common/templates/_helpers.tpl, charts/common/templates/service-cloudarmor.yaml
**Ticket**
[SRE-5480](https://demoforthedaves.atlassian.net/browse/SRE-5480)
- Allow reading definition of `instanceConnectionName` even if `cloudsqlProxy.enabled` is false
- Address space/ident in `service.yaml`
```
diff 0.8.9.yaml 0.9.0-beta.3.yaml                                                                              ✔ 
8c8
<     helm.sh/chart: user-accounts-api-0.8.9
---
>     helm.sh/chart: user-accounts-api-0.9.0-beta.3
24c24
<     helm.sh/chart: user-accounts-api-0.8.9
---
>     helm.sh/chart: user-accounts-api-0.9.0-beta.3
48c48
<     helm.sh/chart: user-accounts-api-0.8.9
---
>     helm.sh/chart: user-accounts-api-0.9.0-beta.3
56c56,57
<     cloud.google.com/backend-config: '{"ports": {"80":"user-accounts-api", …
```
=> SRE-5480/cloudsqlproxy

charts/cloudsql-proxy/Chart.yaml, charts/cloudsql-proxy/schemas/schema.yaml, charts/cloudsql-proxy/values.schema.json
**Ticket**
[SRE-5728](https://demoforthedaves.atlassian.net/browse/SRE-5728)
- feat: Bump cloudsql-proxy chart version to 0.1.1-beta.0 and add schema validation
n/a
n/a
[SRE-5728]: https://demoforthedaves.atlassian.net/browse/SRE-5728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SRE-5728] feat: Bump cloudsql-proxy chart version to 0.1.1-beta.0 and add schema validation

charts/common/Chart.yaml, charts/common/templates/configmap-rproxy.yaml
**Ticket**
[BEI-1120](https://demoforthedaves.atlassian.net/browse/BEI-1120)
Configure nginx to keep X-Forwaded-For and X-Forwaded-Proto as is rather than appending itself to it.
In bff-staging
[BEI-1120]: https://demoforthedaves.atlassian.net/browse/BEI-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BEI-1120] Passthrough XFF headers as is in rproxy

charts/common/Chart.yaml, charts/common/templates/deployment-canary.yaml, charts/common/templates/service-cloudarmor.yaml, charts/common/values.schema.json
**Ticket**
https://demoforthedaves.atlassian.net/browse/BEI-1153
If "canary" is provided on the cloudarmor service section, I want to use that boolean value, even if it is set to false. Only fallback to using the parent chart canary.enabled value if canary is NOT provided in the cloudarmor section.
helm template locally for all scenarios
Attempt using with notification-service first
[DAVE-1]: https://demoforthedaves.atlassian.net/browse/DAVE-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> BEI-1153 - Improve handling of cloudarmor canary logic
