- common/Chart.yaml
- common/templates/deployment.yaml
- common/values.yaml
- Also add some requirement env variables for the dave-logger
- And add a value for deployment container command
> Fix configmap name in Deployment

- common/Chart.yaml
- common/templates/deployment.yaml
- common/values.yaml
And defaults for container liveness and readiness probe ports
> Use name as container name in deployment

- common/Chart.yaml
- common/templates/deployment.yaml
We need to add labels in multiple places:
https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#configuration-1
> Fix tagging deployments with versions

- common/Chart.yaml
- common/templates/deployment.yaml
> Revert "Fix pod annotations in template"

- charts/job/templates/cronjob.yaml
- charts/job/values.yaml
Disable sideCar by default with rename volume variable
> Fix #volumeName variable

- charts/job/templates/cronjob.yaml
- charts/job/values.yaml
- Remove enabled SecurityContext from defaults
- Validate `podSecurityContext` and `securityContext` in template
> Remove enabled SecurityContext from defaults and validate vars in template

- charts/common/templates/deployment.yaml
- charts/common/values.yaml
Resources, livenessProbe, readinessProbe will be optionals with no defaults
> resources, livenessProbe, readinessProbe optional with no defaults

- charts/workflow/Chart.yaml
- charts/workflow/templates/workflowtemplate.yaml
- charts/workflow/values.yaml
https://demoforthedaves.atlassian.net/browse/SRE-1313
Change to workflows chart
- Add option to use a nodeSelector
- Add option to use tolerations
```
nodeSelector:
node_pool: specific-pool-label
tolerations:
- effect: NoSchedule
key: workload
operator: Equal
value: reserverd-node
```
> [SRE-1313] Adding nodeselector to workflow chart

- charts/job/Chart.yaml
- charts/job/templates/cronjob.yaml
- charts/job/templates/job.yaml
[SRE-1358](https://demoforthedaves.atlassian.net/browse/SRE-1358)
Move sidecar to position 0 in containers section
> Sre 1358 sidecar fix

- charts/workflow/Chart.yaml
Bumping workflow chart version to release 0.1.0
> release 0.1.0

- .github/workflows/release.yml
Bump version of chart-releaser
> Bump version of chart-releaser

- charts/common/Chart.yaml
Bump to `common-0.8.1` because `common-0.8.0` tag causes error
> Bump to common-0.8.1

- charts/common/Chart.yaml
> Fix release version

- charts/common/templates/deployment.yaml
**Ticket**
[SRE-1500](https://demoforthedaves.atlassian.net/browse/SRE-1500)
- Introduce the $hasVolumes boolean variable to track if we need volume-related yaml blocks
n/a
n/a
> [SRE-1500] Introduce the $hasVolumes boolean variable to track if we need volume-related yaml blocks

- charts/common/Chart.yaml
- Add conditional for volumeMount: /tmp when `initContainer` is enabled
- Enable `customConfig` through a backing `ConfigMap`.
- Bumped image version for cloudsql proxy so `sh` is available and the `preStop` hook works properly.
> Release 0.8.1

- charts/common/Chart.yaml
- charts/common/templates/deployment.yaml
**Ticket**
NT
- Add subpaths for existing secret mounts.
n/a
n/a
> [NT] Add subpaths for existing secret mounts.

- charts/common/Chart.yaml
**Ticket**
NT
- Release common 0.8.2
n/a
n/a
> [NT] Release common 0.8.2

- charts/common/Chart.yaml
- charts/common/templates/hpa.yaml
[SRE-2172](https://demoforthedaves.atlassian.net/browse/SRE-2172)
[SRE-2172]: https://demoforthedaves.atlassian.net/browse/SRE-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump hpa version to v2

- charts/common/Chart.yaml
- charts/common/templates/service-cloudarmor.yaml
- charts/common/values.yaml
[SRE-2064](https://demoforthedaves.atlassian.net/browse/SRE-2064)
[SRE-2064]: https://demoforthedaves.atlassian.net/browse/SRE-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Cloud IAP option to LB

- charts/job/Chart.yaml
- charts/job/templates/cronjob.yaml
- charts/job/templates/job.yaml
- charts/job/values.yaml
**Ticket**
NT
- Make the `activeDeadlineSeconds` field configurable for jobs/cronjobs.
n/a
n/a
> [NT] Make the `activeDeadlineSeconds` field configurable for jobs/cronjobs.

- charts/job/Chart.yaml
**Ticket**
NT
- Fix name syntax.
n/a
n/a
> [NT] Fix name syntax.

- charts/job/Chart.yaml
Features added in 0.1.5-beta* features
- Adding default to job chart to help debugging, prevent concurrency and prevent execution when updating schedule
```
failedJobsHistoryLimit: "1"
successfulJobsHistoryLimit: "3"
startingDeadlineSeconds: "600"
concurrencyPolicy: "Forbid"
backoffLimit: "1"
ttlSecondsAfterFinished: "3600"
```
- Introduced support for environment variables for side car containers as an opt-in feature through the .Values.sideCar.envFromMainContainer field.
- Add the activeDeadlineSeconds param.
> Release 0.1.5

- charts/tekton-cron-jobs/Chart.yaml
- charts/tekton-cron-jobs/templates/event-listener.yaml
**Ticket**
[NT](https://demoforthedaves.atlassian.net/browse/NT)
add: adding nodeSelector to Eventlistener for cronjobs
n/a
n/a
> [NT] - add: adding nodeSelector to Eventlistener for cronjobs

- charts/common/Chart.yaml
- charts/common/templates/hpa.yaml
- charts/job/Chart.yaml
- charts/job/templates/cronjob.yaml
> Sre 3692/apis

- charts/common/Chart.yaml
- charts/job/Chart.yaml
Stable releases for https://demoforthedaves.atlassian.net/browse/SRE-3692
> Release stable version to support prod upgrades to 1.25 gke version

- charts/common/Chart.yaml
Since these have been validated in General-1 want to bump the version officially rather than as a beta bump
> [BEI-160] Update Common Chart Version

- charts/common/Chart.yaml
Release 0.8.5 to catch with changes in common-0.8.5-beta.*
> Force release of 0.8.5 including common-0.8.5-beta.2

- charts/common/Chart.yaml
- charts/common/templates/workflowtemplate.yaml
- charts/common/values.yaml
- charts/workflow/Chart.yaml
- charts/workflow/templates/workflowtemplate.yaml
- charts/workflow/values.yaml
Output for validation test
[diff.log](https://github.com/dave-inc/charts/files/13206540/diff.log)
[overdraft-orig-render.log](https://github.com/dave-inc/charts/files/13206533/overdraft-orig-render.log)
[overdraft-change-render.log](https://github.com/dave-inc/charts/files/13206512/overdraft-change-render.log)
> SRE-3955: Adding TTL strategy to promote housekeeping in workflows

- charts/kyverno-policies/Chart.yaml
Test bump kyverno to 0.0.1-beta.4
> Bump kyverno to 0.0.1-beta.4

- charts/common/Chart.yaml
- charts/common/templates/deployment.yaml
- charts/common/values.yaml
Support APM Code snippets/Error tracking
https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=go
> Add commit sha and repo url for DD APM Code snippets/Error tracking

- charts/job/Chart.yaml
- charts/job/templates/cronjob.yaml
- charts/job/values.yaml
**Ticket**
[SRE-4080](https://demoforthedaves.atlassian.net/browse/SRE-4080)
- Expose `timeZone` as a configurable field
n/a
n/a
[SRE-4080]: https://demoforthedaves.atlassian.net/browse/SRE-4080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4080] Expose `timeZone` as a configurable field

- charts/job/Chart.yaml
**Ticket**
[SRE-4080](https://demoforthedaves.atlassian.net/browse/SRE-4080)
- Address correct job version
n/a
n/a
[SRE-4080]: https://demoforthedaves.atlassian.net/browse/SRE-4080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4080] Address correct job version

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-pdb.yaml
- charts/kyverno-policies/templates/common-probes.yaml
- charts/kyverno-policies/templates/common-resources.yaml
- charts/kyverno-policies/templates/common-securitycontext.yaml
https://demoforthedaves.atlassian.net/browse/SRE-4354
Refactor current policies, add security context, pdb and probes
> Refactor current policies, add security context, pdb and probes

- charts/kyverno-policies/templates/common-pdb.yaml
- charts/kyverno-policies/templates/common-securitycontext.yaml
Changing names to lowercase in kyverno 0.0.1-beta.5
> Sre 4354/charts1

- charts/job/Chart.yaml
**Ticket**
NT
- Release job-0.1.7
n/a
n/a
> [NT] Release job-0.1.7

- index.yaml
**Ticket**
[SRE-4414](https://demoforthedaves.atlassian.net/browse/SRE-4414)
- Remove kyverno-policies 0.0.1-beta.6
n/a
n/a
[SRE-4414]: https://demoforthedaves.atlassian.net/browse/SRE-4414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4414] Remove kyverno-policies 0.0.1-beta.6

- index.yaml
**Ticket**
[SRE-4414](https://demoforthedaves.atlassian.net/browse/SRE-4414)
- Remove duplicated entries
n/a
n/a
[SRE-4414]: https://demoforthedaves.atlassian.net/browse/SRE-4414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4414] Remove duplicated entries

- index.yaml
**Ticket**
[SRE-4414](https://demoforthedaves.atlassian.net/browse/SRE-4414)
- Remove kyverno-policies-0.0.1-beta.5.tgz
n/a
n/a
[SRE-4414]: https://demoforthedaves.atlassian.net/browse/SRE-4414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4414] Remove kyverno-policies-0.0.1-beta.5.tgz

- index.yaml
**Ticket**
[SRE-4414](https://demoforthedaves.atlassian.net/browse/SRE-4414)
- Remove dupes for the common chart
n/a
n/a
[SRE-4414]: https://demoforthedaves.atlassian.net/browse/SRE-4414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4414] Remove dupes for the common chart

- charts/common/Chart.yaml
- charts/common/templates/deployment.yaml
- charts/common/values.yaml
**Ticket**
[SRE-4413](https://demoforthedaves.atlassian.net/browse/SRE-4413)
- Introduce lifecycles to the main deployment's container
n/a
n/a
[SRE-4413]: https://demoforthedaves.atlassian.net/browse/SRE-4413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4413] Introduce lifecycles to the main deployment's container

- charts/common/Chart.yaml
**Ticket**
NT
- Release common-0.8.6
n/a
n/a
> [NT] Release common-0.8.6

- charts/common/templates/deployment.yaml
**Ticket**
[SRE-4508](https://demoforthedaves.atlassian.net/browse/SRE-4508)
- Define NODE_ENV for the `check-local-secrets` init container
n/a
n/a
[SRE-4508]: https://demoforthedaves.atlassian.net/browse/SRE-4508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4508] Define NODE_ENV for the `check-local-secrets` init container

- charts/common/Chart.yaml
**Ticket**
[SRE-4496](https://demoforthedaves.atlassian.net/browse/SRE-4496)
- Bump chart version. It will be removed afterwards.
n/a
n/a
[SRE-4496]: https://demoforthedaves.atlassian.net/browse/SRE-4496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4496] Bump chart version. It will be removed afterwards.

- charts/job/Chart.yaml
- charts/job/templates/cronjob.yaml
- charts/job/templates/job.yaml
- charts/job/values.yaml
**Ticket**
[SRE-4611](https://demoforthedaves.atlassian.net/browse/SRE-4611)
- Introducing `failOnMissingSecrets` for jobs/cronjobs
n/a
n/a
[SRE-4611]: https://demoforthedaves.atlassian.net/browse/SRE-4611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4611] Introducing `failOnMissingSecrets` for jobs/cronjobs

- charts/kyverno-policies/Chart.yaml
Bump version of the kyverno policies for https://github.com/dave-inc/charts/pull/170
> Bump version of the kyverno policies

- charts/common/Chart.yaml
**Ticket**
[SRE-4617](https://demoforthedaves.atlassian.net/browse/SRE-4617)
- Release common-0.8.7
n/a
n/a
[SRE-4617]: https://demoforthedaves.atlassian.net/browse/SRE-4617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4617] Release common-0.8.7

- charts/kyverno-policies/templates/common-forbid.yaml
- charts/kyverno-policies/templates/common-hpa.yaml
- charts/kyverno-policies/templates/common-pdb.yaml
Exclude HPA and PDB policies from staging applications
https://demoforthedaves.atlassian.net/browse/SRE-4678
> Exclude HPA and PDB policies from staging applications

- index.yaml
**Ticket**
NT
- Remove previous iteration of the dave npd chart
n/a
n/a
> [NT] Remove previous iteration of the dave npd chart

- charts/dave-npd/Chart.yaml
- charts/dave-npd/templates/_helpers.tpl
- charts/dave-npd/templates/main.yaml
**Ticket**
[SRE-4690](https://demoforthedaves.atlassian.net/browse/SRE-4690)
- Add validations
n/a
n/a
[SRE-4690]: https://demoforthedaves.atlassian.net/browse/SRE-4690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4690] Add validations

- charts/dave-npd/Chart.yaml
**Ticket**
[SRE-4690](https://demoforthedaves.atlassian.net/browse/SRE-4690)
- Prod release for `dave-npd`
n/a
n/a
[SRE-4690]: https://demoforthedaves.atlassian.net/browse/SRE-4690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4690] Prod release for `dave-npd`

- charts/dave-npd/Chart.yaml
- charts/dave-npd/values.yaml
**Ticket**
[SRE-4681](https://demoforthedaves.atlassian.net/browse/SRE-4681)
- Add labels to node problem detector
n/a
n/a
[SRE-4681]: https://demoforthedaves.atlassian.net/browse/SRE-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-4681] Add labels to node problem detector

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-probes.yaml
- https://demoforthedaves.atlassian.net/browse/SRE-4830
- Validate startupProbe and release 0.1.0
> Validate startupProbe and release 0.1.0

- charts/common/templates/_helpers.tpl
- charts/common/templates/workflowtemplate.yaml
https://demoforthedaves.atlassian.net/browse/SRE-4987
- Create new variables only when cloudsqlproxy is enabled
> Validate that cloudsqlProxy is enabled

- charts/dave-npd/Chart.yaml
- charts/dave-npd/values.yaml
**Ticket**
NT
- Let node problem detector tolerate all taints
n/a
n/a
> [NT] Let node problem detector tolerate all taints

- charts/common/Chart.yaml
Release 0.8.8 after testing extensively `common-0.8.8-beta.3` part of https://demoforthedaves.atlassian.net/browse/SRE-4864
> Release 0.8.8

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-ingress.yaml
[SRE-4816](https://demoforthedaves.atlassian.net/browse/SRE-4816)
- Change rule name and description to be more explicit
[SRE-4816]: https://demoforthedaves.atlassian.net/browse/SRE-4816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SRE-4816 - Naming and working

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-forbid.yaml
- charts/kyverno-policies/templates/common-hpa.yaml
- charts/kyverno-policies/templates/common-ingress.yaml
- charts/kyverno-policies/templates/common-labels.yaml
- charts/kyverno-policies/templates/common-probes.yaml
- charts/kyverno-policies/templates/common-resources.yaml
- charts/kyverno-policies/templates/common-security-context.yaml
- charts/kyverno-policies/values.yaml
https://demoforthedaves.atlassian.net/browse/SRE-5057
- Switch to validate `HPA` by name
- Validate `ingressClassName`, annotation in `ingress` and allow Cloud Armor to pass
- Group all policies under "Best practices"
- Moving exclusion to defaults in values.yaml so we can customize per cluster
> 0.1.1-beta.4 - Improvement to ingress,hpa and exclusions defaults

- charts/kyverno-policies/templates/common-labels.yaml
- charts/kyverno-policies/templates/common-security-context.yaml
- https://demoforthedaves.atlassian.net/browse/SRE-5057
- Add more exclusion variable
> Add more exclusion to variable

- charts/kyverno-policies/Chart.yaml
> Bump to kyverno 0.1.1-beta.5

- .github/workflows/release.yml
so we don't dirty master branch during development
> [NT] adding workflow dispatch to allow manual releases from feature branches

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-forbid.yaml
- charts/kyverno-policies/templates/common-hpa.yaml
- charts/kyverno-policies/templates/common-ingress.yaml
- charts/kyverno-policies/templates/common-labels.yaml
- charts/kyverno-policies/templates/common-probes.yaml
- charts/kyverno-policies/templates/common-resources.yaml
- charts/kyverno-policies/templates/common-security-context.yaml
- charts/kyverno-policies/values.yaml
https://demoforthedaves.atlassian.net/browse/SRE-5083
- Allow variables to be defined at the policy level
```
policies.kyverno.io/category: Best Practices
policies.kyverno.io/severity: medium
validationFailureAction: {{ .Values.policySets.common.validationFailureAction }}
```
- Fix bug where preconditions are applied to Probes
- Fix bug in HPA were we assign a default value to prevent Errors
> Move variables to policy level, preconditions and hpa error

- .github/workflows/release.yml
- README.md
- charts/common/Chart.yaml
- charts/common/templates/ingress-cloudarmor.yaml
- charts/common/values.yaml
https://demoforthedaves.atlassian.net/browse/BEI-719
- Added multi host capability for cloudArmor ingress in common charts
- Should be backwards compatible
- will drop the feature suffix to version once tested on a pilot
> [BEI-719] added capability for cloudArmor to have multiple hosts

- charts/common/Chart.yaml
- charts/common/templates/service-cloudarmor.yaml
Adding logs
[RenderOld.log](https://github.com/user-attachments/files/17759036/RenderOld.log)
[RenderNew.log](https://github.com/user-attachments/files/17778096/RenderNew.log)
[diff.log](https://github.com/user-attachments/files/17778097/diff.log)
> SRE-5137: Enhancing CA Service to render based on the backend services added

- charts/common/Chart.yaml
- charts/common/templates/service-cloudarmor.yaml
- charts/common/values.yaml
Here are the logs:
[RenderOld.log](https://github.com/user-attachments/files/17875696/RenderOld.log)
[RenderNew.log](https://github.com/user-attachments/files/17875701/RenderNew.log)
[diff.log](https://github.com/user-attachments/files/17875702/diff.log)
> SRE-5322: Exposing targetPort to CA backend service

- charts/common/Chart.yaml
- charts/common/templates/deployment.yaml
**Ticket**
[SRE-5325](https://demoforthedaves.atlassian.net/browse/SRE-5325)
- Fix duplicate lifecycle
[SRE-5325]: https://demoforthedaves.atlassian.net/browse/SRE-5325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SRE-5325/lifecycle

- index.yaml
**Ticket**
NT
- Removed common-0.8.10-beta.3
n/a
n/a
> [NT] Removed common-0.8.10-beta.3

- charts/csm-edgeproxy/Chart.yaml
- charts/csm-edgeproxy/templates/_helpers.tpl
- charts/csm-edgeproxy/templates/autoscaling-v2.yaml
- charts/csm-edgeproxy/templates/deployment.yaml
- charts/csm-edgeproxy/templates/pdb.yaml
- charts/csm-edgeproxy/templates/role.yaml
- charts/csm-edgeproxy/templates/service.yaml
- charts/csm-edgeproxy/templates/serviceaccount.yaml
- charts/csm-edgeproxy/values.yaml
This adds a chart that can be used to deploy istio's gateway.
> [BEI-838] Add a chart for Istio gateway deployment

- charts/common/Chart.yaml
- charts/common/templates/service-cloudarmor.yaml
Here are the logs:
[RenderpapiOld.log](https://github.com/user-attachments/files/18118661/RenderpapiOld.log)
[RenderpapiNew.log](https://github.com/user-attachments/files/18118769/RenderpapiNew.log)
[diff.log](https://github.com/user-attachments/files/18118771/diff.log)
> SRE-5344: Fixing CA service template same backend service name scenario

- charts/csm-edgeproxy/Chart.yaml
- charts/csm-edgeproxy/templates/service.yaml
Service resource is missing required field `name`
> Fix Service in csm-edgeproxy

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-labels.yaml
- charts/kyverno-policies/values.yaml
**Ticket**
[SRE-5373](https://demoforthedaves.atlassian.net/browse/SRE-5373)
- Remove whitelist allow reporter to show failures in SRE namespaces
- Update label policy search for label in metadata and spec
[SRE-5373]: https://demoforthedaves.atlassian.net/browse/SRE-5373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kyverno Update label policy and remove namespace whitelists

- charts/csm-edgeproxy/Chart.yaml
**Ticket**
[BEI-838](https://demoforthedaves.atlassian.net/browse/BEI-838)
- Bump kyverno version
[BEI-838]: https://demoforthedaves.atlassian.net/browse/BEI-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BEI-838/bump-version

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-public-access.yaml
- charts/kyverno-policies/values.yaml
**Ticket**
[SRE-5373](https://demoforthedaves.atlassian.net/browse/SRE-5373)
- Fix exclusions and annotation to public-access
[SRE-5373]: https://demoforthedaves.atlassian.net/browse/SRE-5373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kyverno - Fix exclusions and annotation to public-access

- .github/workflows/lint.yml
- charts/common/Chart.yaml
- charts/common/templates/backendconfig.yaml
- charts/common/templates/certificate-cloudarmor.yaml
- charts/common/templates/frontendconfig.yaml
- charts/common/templates/gateway-cloudarmor.yaml
- charts/common/templates/ingress-cloudarmor.yaml
- charts/common/templates/service-cloudarmor.yaml
- charts/common/values.schema.json
- charts/common/values.yaml
> Sec 6157 add json schema for cloud armor helm chart

- .github/PULL_REQUEST_TEMPLATE.md
- CODEOWNERS
- No ticket
- Adding Codeowners and Pull request template
> Sre nt/codeowners

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/values.yaml
**Ticket**
[SRESUP-327](https://demoforthedaves.atlassian.net/browse/SRESUP-327)
- Fix label skip for labels policy
[SRESUP-327]: https://demoforthedaves.atlassian.net/browse/SRESUP-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SRESUP-327/label-fix

- charts/common/templates/_helpers.tpl
- charts/common/templates/configmap-rproxy.yaml
- charts/common/templates/deployment-rproxy.yaml
- charts/common/templates/hpa-rproxy.yaml
- charts/common/values.yaml
**Ticket**
[BEI-979](https://demoforthedaves.atlassian.net/browse/BEI-979)
Create *-nginx reverse proxy deployment.
[DAVE-1]: https://demoforthedaves.atlassian.net/browse/DAVE-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BEI-979]: https://demoforthedaves.atlassian.net/browse/BEI-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BEI-979] Add nginx reverse proxy for canary

- .github/workflows/json_schema_bundle.yml
- .github/workflows/json_schema_bundler.yml
- README.md
- charts/common/Chart.yaml
- charts/common/schemas/schema.yaml
- charts/common/values.schema.json
**Ticket**
[SRE-5686](https://demoforthedaves.atlassian.net/browse/SRE-5686)
- Introduce json schema bundle creation/update + validation
n/a
n/a
[SRE-5686]: https://demoforthedaves.atlassian.net/browse/SRE-5686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-5686] Introduce json schema bundle creation/update + validation

- charts/common/Chart.yaml
- charts/common/templates/service-cloudarmor.yaml
**Ticket**
[BEI-1117](https://demoforthedaves.atlassian.net/browse/DAVE-1)
[DAVE-1]: https://demoforthedaves.atlassian.net/browse/DAVE-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BEI-1117]: https://demoforthedaves.atlassian.net/browse/BEI-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BEI-1117] Fix canary in service-cloudarmor.yaml

- charts/job/Chart.yaml
- charts/job/schemas/schema.yaml
- charts/job/values.schema.json
**Ticket**
[SRE-5728](https://demoforthedaves.atlassian.net/browse/SRE-5728)
- feat: bump version to 0.2.2-beta.0 and add JSON schema for environment validation
n/a
n/a
[SRE-5728]: https://demoforthedaves.atlassian.net/browse/SRE-5728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SRE-5728] feat: bump version to 0.2.2-beta.0 and add JSON schema for environment validation

- charts/common/Chart.yaml
- charts/common/templates/service-cloudarmor.yaml
**Ticket**
https://demoforthedaves.atlassian.net/browse/BEI-1153
Missing -rproxy suffix on .Release.Name
local helm template . command. Also tested beta version of chart on notification-service
Verify using notificaiton-service
[DAVE-1]: https://demoforthedaves.atlassian.net/browse/DAVE-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BEI-1153 - Fix missing -rproxy suffix

- charts/kyverno-policies/Chart.yaml
- charts/kyverno-policies/templates/common-app-labels.yaml
- charts/kyverno-policies/templates/common-forbid.yaml
- charts/kyverno-policies/templates/common-labels-v2.yaml
- charts/kyverno-policies/templates/common-labels.yaml
- charts/kyverno-policies/templates/common-resources.yaml
- charts/kyverno-policies/templates/common-security-context.yaml
- charts/kyverno-policies/values.yaml
**Ticket**
[SRE-5801](https://demoforthedaves.atlassian.net/browse/SRE-5801)
Adding app label policy to deploys and crons
Created manually the policy in`gke-devel-1 `cluster and confirmed the proper validation, it can be checked here:
https://policy-reports.gke-devel-1.trydave.com/#/kyverno-plugin/8c22ef0d-6352-49d7-b3cf-5d65b7f76173
ArgoCD
[SRE-5801]: https://demoforthedaves.atlassian.net/browse/SRE-5801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SRE-5801: Adding app label policy to deploys and crons
